sudo: false
language: python
python:
    - "2.7"
    - "3.6"
install:
    - env | sort
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION arrow flask flask-socketio mock mongodb nose numpy networkx pip pymongo pyparsing redis requests six sklearn
    - source activate test-environment
    - pip install behave coverage coveralls huey hyperopt ldap3 nose-exclude tensorflow toyplot
script:
    - coverage run --source samlab -m behave --tags=-wip
    - coverage report
after_script:
    - coveralls
